spring:
  config:
    import: application-secret.properties
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: ${JWT_SECRET}