name: ci
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SetUp JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Set Environment Variables
        run: |
          cd ./src/main/resources
          echo "${{ secrets.ENV }}" > ./application-secret.properties

      - name: Build with Gradle
        run: |
          if [ "${{ github.ref_name }}" = "dev" ]; then
            PROFILE="dev"
          elif [ "${{ github.ref_name }}" = "main" ]; then
            PROFILE="prod"
          fi
          ./gradlew clean build -Pprofile=$PROFILE